plugins {
    id 'privactivity.java-conventions'
    id 'privactivity.library-conventions'
}

dependencies {
    implementation project(':privactivity-domain')
    implementation project(':privactivity-store-domain')

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'org.slf4j:slf4j-api'

    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.assertj:assertj-core'
}