plugins {
    id 'privactivity.java-conventions'
    id 'privactivity.library-conventions'
}

dependencies {
    implementation project(':privactivity-store-domain')
    implementation project(':privactivity-domain')

    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.eclipse.store:integrations-spring-boot3'
    implementation 'org.eclipse.serializer:serializer'
    implementation 'org.slf4j:slf4j-api'

    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}