privactivity.store.climb.storage-directory=${java.io.tmpdir}/${random.int}/climb
privactivity.store.repo.activity.storage-directory=${java.io.tmpdir}/${random.int}/fit
privactivity.store.metadata.storage-directory=${java.io.tmpdir}/${random.int}/metadata
privactivity.store.json.storage-directory=${java.io.tmpdir}/${random.int}/json
privactivity.tiles.tile-width-degrees=0.02
privactivity.tiles.tile-height-degrees=0.02
privactivity.fit.import.directory={java.io.tmpdir}/${random.int}/fit-import-directory