server.port=${PORT:8090}
privactivity.store.climb.storage-directory=/climb
privactivity.store.repo.activity.storage-directory=/fit
privactivity.store.metadata.storage-directory=/metadata
privactivity.store.json.storage-directory=/json
privactivity.tiles.tile-width-degrees=0.01
privactivity.tiles.tile-height-degrees=0.005
privactivity.fit.import.directory=/fit-import-directory
privactivity.fit.import.scheduler.initiaDelay=10s
privactivity.users.file.path=/tmp/users.json
privactivity.bootstrap.admin-password-file.path=/tmp/admin-password.txt
spring.devtools.livereload.port=45730
